# -*- coding: utf-8 -*-
"""PrakAlgo7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktBX2PRc2QHkyUCI9DQtkXjlep1kRpYU
"""

def hitung_faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * hitung_faktorial(n - 1)

# Meminta input dari pengguna
bilangan = int(input("Masukkan bilangan untuk menghitung faktorial: "))

# Memeriksa apakah bilangan non-negatif
if bilangan < 0:
    print("Faktorial tidak terdefinisi untuk bilangan negatif.")
else:
    hasil_faktorial = hitung_faktorial(bilangan)
    print(f"Faktorial dari {bilangan} adalah {hasil_faktorial}")

def hitung_vokal_konsonan(kalimat):
    # Inisialisasi hitungan
    jumlah_vokal = 0
    jumlah_konsonan = 0

    # Mengonversi kalimat menjadi huruf kecil untuk mempermudah perhitungan
    kalimat = kalimat.lower()

    # Melakukan iterasi untuk setiap karakter dalam kalimat
    for karakter in kalimat:
        # Memeriksa apakah karakter adalah huruf
        if karakter.isalpha():
            # Memeriksa apakah karakter adalah vokal
            if karakter in 'aeiou':
                jumlah_vokal += 1
            else:
                jumlah_konsonan += 1

    return jumlah_vokal, jumlah_konsonan

# Meminta input kalimat dari pengguna
kalimat_input = input("Masukkan sebuah kalimat: ")

# Memanggil fungsi dan mendapatkan hasil
vokal, konsonan = hitung_vokal_konsonan(kalimat_input)

# Menampilkan hasil
print(f"Jumlah huruf vokal: {vokal}")
print(f"Jumlah huruf konsonan: {konsonan}")

def kubik(angka):
    return angka**3

def cek_habis_dibagi_tiga(angka):
    if angka % 3 == 0:
        return kubik(angka)
    else:
        return False

# Meminta input dari pengguna
input_angka = int(input("Masukkan suatu angka: "))

# Memanggil fungsi kedua dan menampilkan hasil
hasil = cek_habis_dibagi_tiga(input_angka)
if hasil is not False:
    print(f"Nilai kubik dari {input_angka} adalah {hasil}")
else:
    print("False")