# -*- coding: utf-8 -*-
"""prakalgo5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qhe6iL3ZIaAEfpju931EOZyNOeONjgv_
"""

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @       @        @    @@     @    @@     @        @     @     @")

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @       @        @    @@     @    @@     @        @     @     @")


def cetak_urutan(angka_pertama, angka_kedua, jumlah):
    print("berikut urutannya")
    print(angka_pertama)
    print("berikut urutannya")
    print(angka_kedua)

    for i in range(2, jumlah):
        angka_baru = angka_pertama + angka_kedua
        angka_pertama, angka_kedua = angka_kedua, angka_baru

        print("berikut urutannya")
        print(angka_baru)

def main():
    jumlah_bilangan = int(input("Masukkan Jumlah bilangan: "))
    angka_pertama = int(input("Masukkan angka pertama: "))
    angka_kedua = int(input("Masukkan angka kedua: "))
    cetak_urutan(angka_pertama, angka_kedua, jumlah_bilangan)

if __name__ == "__main__":
    main()

nama = input("Nama: ")
jam_masuk = int(input("Jam masuk kerja: "))
menit_masuk = int(input("Menit masuk kerja: "))
jam_keluar = int(input("Jam keluar kerja: "))
menit_keluar = int(input("Menit keluar kerja: "))

jam_kerja = jam_keluar - jam_masuk
if menit_keluar < menit_masuk:
    jam_kerja -= 1

gaji_per_hari = 175000
lembur = 0
if jam_kerja > 8:
    lembur = (jam_kerja - 8) * 15000
    jam_kerja = 8

print(f"Selamat {jam_masuk:02d}:{menit_masuk:02d} {nama}")
print(f"Jam keluar kerja: {jam_keluar:02d}:{menit_keluar:02d}")
print("----- rincian gaji -----")
print(f"Nama: {nama}")
print(f"Waktu kerja: {jam_kerja} jam ({jam_masuk:02d}:{menit_masuk:02d} sd {jam_keluar:02d}:{menit_keluar:02d})")
print(f"Gaji perhari: Rp {gaji_per_hari}")
print(f"Lembur: Rp {lembur} ({jam_kerja - 8} jam x @Rp 15.000)")