# -*- coding: utf-8 -*-
"""prakalgo13.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_rIhYhd3Q8qGnjSS1mPMbN2tds5N5hY
"""

nilai_siswa = [85, 90, 78, 92, 88]

rata_rata_kelas = sum(nilai_siswa) / len(nilai_siswa)

print(f"Rata-rata nilai kelas: {rata_rata_kelas:.1f}")

siswa_di_atas_rata = [nilai for nilai in nilai_siswa if nilai > rata_rata_kelas]

print(f"Siswa yang mendapatkan nilai di atas rata-rata: {siswa_di_atas_rata}")