# -*- coding: utf-8 -*-
"""PrakAlgo2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tDABZXBpnHWkhedcu2aLmcsMjA_bnxsV
"""

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @       @         @    @@     @    @@     @        @     @     @")

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @       @         @    @@     @    @@     @        @     @     @")

import math

def hitung_sisi_siku_siku():
    print("Selamat datang di Kalkulator Pythagoras!")
    print("Pilih apa yang ingin Anda hitung:")
    print("1. Panjang Sisi C (sisi miring)")
    print("2. Panjang Sisi A atau B")

    pilihan = int(input("Masukkan pilihan (1/2): "))

    if pilihan == 1:
        sisi_a = float(input("Masukkan panjang sisi A: "))
        sisi_b = float(input("Masukkan panjang sisi B: "))
        panjang_sisi_c = math.sqrt(sisi_a**2 + sisi_b**2)
        print(f"Panjang sisi C (sisi miring) adalah: {panjang_sisi_c}")
    elif pilihan == 2:
        sisi_c = float(input("Masukkan panjang sisi C (sisi miring): "))
        sisi_a_b = float(input("Masukkan panjang salah satu sisi A atau B: "))
        panjang_sisi = math.sqrt(sisi_c**2 - sisi_a_b**2)
        print(f"Panjang sisi A atau B adalah: {panjang_sisi}")
    else:
        print("Pilihan tidak valid. Silakan pilih 1 atau 2.")

if __name__ == "__main__":
    hitung_sisi_siku_siku()

angka1 = float(input("Masukkan angka pertama: "))
angka2 = float(input("Masukkan angka kedua: "))
angka3 = float(input("Masukkan angka ketiga: "))


angka_terbesar = max(angka1, angka2, angka3)


print(f"Angka terbesar adalah: {angka_terbesar}")

import math

def hitung_a(b, c):
    return math.sqrt(c*2 - b*2)

def hitung_b(a, c):
    return math.sqrt(c*2 - a*2)

def hitung_c(a, b):
    return math.sqrt(a*2 + b*2)

def main():
    print("Menghitung Pytagoras")
    print("a.) menghitung sisi a")
    print("b.) menghitung sisi b")
    print("c.) menghitung sisi c")

    opsi = str(input("masukan opsi : "))

    #menghitung sisi a
    if opsi == "a":
        b = float(input("Masukan sisi b : "))
        c = float(input("Masukan sisi c : "))
        while c < b:
            print("Nilai c harus lebih besar atau sama dengan nilai b.")
            c = float(input("Masukkan nilai sisi c: "))
        sisi_a = hitung_a(b, c)
        print(f"Sisi a = {sisi_a}")
    #mengitung sisi b
    elif opsi == "b":
        a = float(input("masukan sisi a : "))
        c = float(input("masukan sisi c : "))
        while c < a:
            print("Nilai c harus lebih besar atau sama dengan nilai a.")
            c = float(input("Masukkan nilai sisi c: "))
        sisi_b = hitung_b(a, c)
        print(f"Sisi b = {sisi_b}")
    #menghitung sisi c
    elif opsi == "c":
        a = float(input("masukan sisi a : "))
        b = float(input("masukan sisi b : "))
        sisi_c =  hitung_c(a, b)
        print("sisi c = ", sisi_c)
    else:
        print("opsi tidak valid.")

if __name__ == "__main__":
    main()