# -*- coding: utf-8 -*-
"""prakalgo13.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beklrXIiJiFQJxSSFC9jDJls-Z02hMiS
"""

def konversi_mata_uang(jumlah_local, kurs):
    jumlah_asing = jumlah_local / kurs
    return jumlah_asing

jumlah_rupiah = float(input("Masukkan jumlah uang dalam Rupiah: "))

kurs_dolar_terhadap_rupiah = float(input("Masukkan kurs Dolar terhadap Rupiah: "))

jumlah_dolar = konversi_mata_uang(jumlah_rupiah, kurs_dolar_terhadap_rupiah)

print(f"Jumlah uang dalam Dolar: ${jumlah_dolar:.15f}")