# -*- coding: utf-8 -*-
"""PrakAlgo4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3w0qYoYydwXdIpQqw8mMJujbtNfwKLt
"""

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @       @        @    @@     @    @@     @        @     @     @")


def desimal_ke_biner(angka):
    biner = ""
    while angka > 0:
        sisa = angka % 2
        biner = str(sisa) + biner
        angka = angka // 2
    return biner

def biner_ke_desimal(biner):
    desimal = 0
    panjang = len(biner)
    for i in range(panjang):
        digit = int(biner[i])
        desimal += digit * (2 ** (panjang - i - 1))
    return desimal

while True:
    print("Pilih angka 1-3:")
    print("1. Desimal ke Biner")
    print("2. Biner ke Desimal")
    print("3. Keluar")

    pilihan = input("Masukkan pilihan 1-3 (1/2/3): ")

    if pilihan == "1":
        angka = int(input("Masukkan angka desimal: "))
        biner = desimal_ke_biner(angka)
        print("Hasil konversi ke biner:", biner)
    elif pilihan == "2":
        biner = input("Masukkan bilangan biner: ")
        desimal = biner_ke_desimal(biner)
        print("Hasil konversi ke desimal:", desimal)
    elif pilihan == "3":
        print("Thank you ya sayang <3")
        break
    else:
        print("Pilihan tidak valid. Silakan pilih 1, 2, atau 3.")

print("p valo bang")

# Meminta pengguna untuk memasukkan angka-angka
angka = input("Masukkan angka-angka (dipisahkan oleh spasi): ")
angka = angka.split()  # Membagi input menjadi list angka

# Menginisialisasi variabel terdapat_genap
terdapat_genap = False

# Memeriksa apakah ada angka genap dalam list dengan loop while
i = 0
while i < len(angka):
    if int(angka[i]) % 2 == 0:
        terdapat_genap = True
        break
    i += 1

if terdapat_genap:
    print("Terdapat angka genap dalam list.")
else:
    print("Tidak terdapat angka genap dalam list.")