# -*- coding: utf-8 -*-
"""prakAlgo8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdaR09_n3aYsFFEFOAP5oPtPmTsDylP6
"""

def karakter_ganjil(input_string):
    result = ""
    for i in range(len(input_string)):
        if i % 2 == 1:
            result += input_string[i]
    return result

user_input = input("Masukkan sebuah kata atau kalimat: ")

hasil = karakter_ganjil(user_input)

print("Karakter dengan index ganjil:", hasil)

print("PROGRAM MENGHITUNG JUMLAH RANGE")

angka_pertama = int(input("Masukkan angka pertama: "))
angka_kedua = int(input("Masukkan angka kedua: "))

jumlah_range = sum(range(angka_pertama, angka_kedua + 1))

print("Jumlah range adalah:", jumlah_range)