# -*- coding: utf-8 -*-
"""prakalgo13.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwwXJGyqLrR4_0IXxdhwVcL5ILuHBDFN
"""

proyek_dalam_pengerjaan = []

while True:
    nama_proyek = input("Masukkan nama proyek (ketik 'selesai' untuk mengakhiri): ")
    if nama_proyek.lower() == 'selesai':
        break
    estimasi_waktu = int(input("Masukkan estimasi waktu proyek (dalam hari): "))
    status = "dalam pengerjaan"

    proyek = {"nama": nama_proyek, "estimasi_waktu": estimasi_waktu, "status": status}
    proyek_dalam_pengerjaan.append(proyek)

proyek_dalam_pengerjaan = sorted(proyek_dalam_pengerjaan, key=lambda x: x["estimasi_waktu"])

print("Proyek Dalam Pengerjaan (Diurutkan berdasarkan Estimasi Waktu):")
for proyek in proyek_dalam_pengerjaan:
    print(f"Nama: {proyek['nama']}, Estimasi Waktu: {proyek['estimasi_waktu']} hari, Status: {proyek['status']}")