# -*- coding: utf-8 -*-
"""PrakAlgo6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W5KbDD1x7tsPle5TbALhDhHzhW5NVcAl
"""

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @        @       @    @@     @    @@     @        @     @     @")

print("ganjil -> jarak tempuh")
v0 = float(input("masukan vo="))

t= float(input("masukan t="))
a= float(input("masukan a="))

s=v0*t+0.5*a*t**2

print(f"jika kecepatan awal={v0}m/s,percepatan={a}m/s^2 dan waktu={t} s, maka jarak tempuh adalah{s}meter")

print ("@   @          @           @@    @     @@    @         @          @     @")
print ("@   @        @  @          @ @   @     @ @   @        @  @        @ @   @")
print ("@@@@@       @@@@@@         @  @  @     @  @  @       @ @@ @       @  @  @")
print ("@   @      @      @        @   @ @     @   @ @      @      @      @   @ @")
print ("@   @     @        @       @    @@     @    @@     @        @     @     @")
import math

def luas_permukaan_kubus(sisi):
    return 6 * sisi ** 2

def luas_permukaan_balok(panjang, lebar, tinggi):
    return 2 * (panjang * lebar + panjang * tinggi + lebar * tinggi)

def luas_permukaan_tabung(jari_jari, tinggi):
    return 2 * math.pi * jari_jari * (jari_jari + tinggi)

def luas_permukaan_kerucut(jari_jari, tinggi):
    s = math.sqrt(jari_jari**2 + tinggi**2)
    return math.pi * jari_jari * (jari_jari + s)

def luas_permukaan_bola(jari_jari):
    return 4 * math.pi * jari_jari ** 2

def main():
    print("Program Menghitung Luas Permukaan Bangun Ruang")
    print("Pilih bangun ruang:")
    print("1. Kubus")
    print("2. Balok")
    print("3. Tabung")
    print("4. Kerucut")
    print("5. Bola")

    pilihan = int(input("Masukkan nomor bangun ruang (1/2/3/4/5): "))

    if pilihan == 1:
        sisi = float(input("Masukkan panjang sisi kubus: "))
        hasil = luas_permukaan_kubus(sisi)
    elif pilihan == 2:
        panjang = float(input("Masukkan panjang balok: "))
        lebar = float(input("Masukkan lebar balok: "))
        tinggi = float(input("Masukkan tinggi balok: "))
        hasil = luas_permukaan_balok(panjang, lebar, tinggi)
    elif pilihan == 3:
        jari_jari = float(input("Masukkan jari-jari tabung: "))
        tinggi = float(input("Masukkan tinggi tabung: "))
        hasil = luas_permukaan_tabung(jari_jari, tinggi)
    elif pilihan == 4:
        jari_jari = float(input("Masukkan jari-jari kerucut: "))
        tinggi = float(input("Masukkan tinggi kerucut: "))
        hasil = luas_permukaan_kerucut(jari_jari, tinggi)
    elif pilihan == 5:
        jari_jari = float(input("Masukkan jari-jari bola: "))
        hasil = luas_permukaan_bola(jari_jari)
    else:
        print("Pilihan tidak valid.")
        return

    print(f"Luas permukaan bangun ruang adalah: {hasil:.2f}")

if __name__ == "__main__":
    main()